#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
    M3E_CATALOG_STORY_FOUNDATION = 0,
    M3E_CATALOG_STORY_DISPLAY_STRESS = 1,
    M3E_CATALOG_STORY_COMPONENTS = 2,
    M3E_CATALOG_STORY_CALORIES = 3,
    M3E_CATALOG_STORY_CALCULATOR = 4,
    M3E_CATALOG_STORY_WORKOUT = 5,
    M3E_CATALOG_STORY_INPUTS = 6,
    M3E_CATALOG_STORY_VOICE = 7,
    M3E_CATALOG_STORY_NAVIGATION = 8,
    M3E_CATALOG_STORY_SYSTEM = 9,
    M3E_CATALOG_STORY_TRANSFORMING_LIST = 10,
    M3E_CATALOG_STORY_EXPRESSIVE_DEPTH = 11,
    M3E_CATALOG_STORY_MOCKUP_HYDRATION = 12,
    M3E_CATALOG_STORY_MOCKUP_FOCUS = 13,
    M3E_CATALOG_STORY_MOCKUP_TRAVEL = 14,
    M3E_CATALOG_STORY_MOCKUP_MUSIC = 15,
};

void m3e_catalog_show(lv_obj_t* screen, int story);

#ifdef __cplusplus
}
#endif
