#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
    M3E_CATALOG_STORY_FOUNDATION = 0,
    M3E_CATALOG_STORY_DISPLAY_STRESS = 1,
    M3E_CATALOG_STORY_COMPONENTS = 2,
    M3E_CATALOG_STORY_CALORIES = 3,
    M3E_CATALOG_STORY_CALCULATOR = 4,
    M3E_CATALOG_STORY_WORKOUT = 5,
    M3E_CATALOG_STORY_INPUTS = 6,
    M3E_CATALOG_STORY_VOICE = 7,
    M3E_CATALOG_STORY_NAVIGATION = 8,
    M3E_CATALOG_STORY_SYSTEM = 9,
    M3E_CATALOG_STORY_TRANSFORMING_LIST = 10,
    M3E_CATALOG_STORY_EXPRESSIVE_DEPTH = 11,
    M3E_CATALOG_STORY_MOCKUP_HYDRATION = 12,
    M3E_CATALOG_STORY_MOCKUP_FOCUS = 13,
    M3E_CATALOG_STORY_MOCKUP_TRAVEL = 14,
    M3E_CATALOG_STORY_MOCKUP_MUSIC = 15,
    M3E_CATALOG_STORY_OS_HOME = 16,
    M3E_CATALOG_STORY_OS_LIVE_CARDS = 17,
    M3E_CATALOG_STORY_OS_LAUNCHER = 18,
    M3E_CATALOG_STORY_OS_CONTROL_CENTER = 19,
    M3E_CATALOG_STORY_OS_APP_MANAGER = 20,
    M3E_CATALOG_STORY_OS_VOICE = 21,
    M3E_CATALOG_STORY_OS_APP_DETAIL = 22,
    M3E_CATALOG_STORY_OS_INSTALL_PROGRESS = 23,
    M3E_CATALOG_STORY_OS_CRASH_RECOVERY = 24,
    M3E_CATALOG_STORY_OS_NOTIFICATION = 25,
    M3E_CATALOG_STORY_OS_PERMISSION_REVIEW = 26,
    M3E_CATALOG_STORY_OS_ACTION_REVIEW = 27,
    M3E_CATALOG_STORY_OS_ERROR = 28,
    M3E_CATALOG_STORY_OS_VOICE_THINKING = 29,
    M3E_CATALOG_STORY_OS_VOICE_REVIEW = 30,
    M3E_CATALOG_STORY_OS_VOICE_BUILD = 31,
    M3E_CATALOG_STORY_OS_VOICE_RESULT = 32,
    M3E_CATALOG_STORY_COLOR_BARS = 33,
};

typedef struct {
    lv_obj_t* primary_action;
    lv_obj_t* cancel_action;
    lv_obj_t* level_ring;
} m3e_voice_runtime_view_t;

void m3e_catalog_show(lv_obj_t* screen, int story);
void m3e_catalog_show_voice_runtime(
    lv_obj_t* screen,
    int phase,
    const char* transcript,
    const char* response,
    m3e_voice_runtime_view_t* view);

#ifdef __cplusplus
}
#endif
