// Generated by tools/weather_foundations/generate.py. DO NOT EDIT.
#pragma once

#include "lvgl.h"
#include "m3e/generated/weather_icons.hpp"

#include <cstdint>

namespace m3e {

const lv_image_dsc_t* weather_icon_asset(
    generated::WeatherIcon icon,
    std::int32_t size);

}  // namespace m3e
