// Generated by tools/weather_foundations/generate.py. DO NOT EDIT.
#include "m3e/assets/weather_icon_assets.hpp"

#include <array>
#include <cstddef>

extern "C" {
extern const lv_image_dsc_t m3e_weather_icon_condition_clear_day_18;
extern const lv_image_dsc_t m3e_weather_icon_condition_clear_day_24;
extern const lv_image_dsc_t m3e_weather_icon_condition_clear_day_32;
extern const lv_image_dsc_t m3e_weather_icon_condition_clear_day_64;
extern const lv_image_dsc_t m3e_weather_icon_condition_clear_night_18;
extern const lv_image_dsc_t m3e_weather_icon_condition_clear_night_24;
extern const lv_image_dsc_t m3e_weather_icon_condition_clear_night_32;
extern const lv_image_dsc_t m3e_weather_icon_condition_clear_night_64;
extern const lv_image_dsc_t m3e_weather_icon_condition_partly_cloudy_day_18;
extern const lv_image_dsc_t m3e_weather_icon_condition_partly_cloudy_day_24;
extern const lv_image_dsc_t m3e_weather_icon_condition_partly_cloudy_day_32;
extern const lv_image_dsc_t m3e_weather_icon_condition_partly_cloudy_day_64;
extern const lv_image_dsc_t m3e_weather_icon_condition_partly_cloudy_night_18;
extern const lv_image_dsc_t m3e_weather_icon_condition_partly_cloudy_night_24;
extern const lv_image_dsc_t m3e_weather_icon_condition_partly_cloudy_night_32;
extern const lv_image_dsc_t m3e_weather_icon_condition_partly_cloudy_night_64;
extern const lv_image_dsc_t m3e_weather_icon_condition_cloudy_18;
extern const lv_image_dsc_t m3e_weather_icon_condition_cloudy_24;
extern const lv_image_dsc_t m3e_weather_icon_condition_cloudy_32;
extern const lv_image_dsc_t m3e_weather_icon_condition_cloudy_64;
extern const lv_image_dsc_t m3e_weather_icon_condition_overcast_18;
extern const lv_image_dsc_t m3e_weather_icon_condition_overcast_24;
extern const lv_image_dsc_t m3e_weather_icon_condition_overcast_32;
extern const lv_image_dsc_t m3e_weather_icon_condition_overcast_64;
extern const lv_image_dsc_t m3e_weather_icon_condition_fog_18;
extern const lv_image_dsc_t m3e_weather_icon_condition_fog_24;
extern const lv_image_dsc_t m3e_weather_icon_condition_fog_32;
extern const lv_image_dsc_t m3e_weather_icon_condition_fog_64;
extern const lv_image_dsc_t m3e_weather_icon_condition_drizzle_18;
extern const lv_image_dsc_t m3e_weather_icon_condition_drizzle_24;
extern const lv_image_dsc_t m3e_weather_icon_condition_drizzle_32;
extern const lv_image_dsc_t m3e_weather_icon_condition_drizzle_64;
extern const lv_image_dsc_t m3e_weather_icon_condition_rain_18;
extern const lv_image_dsc_t m3e_weather_icon_condition_rain_24;
extern const lv_image_dsc_t m3e_weather_icon_condition_rain_32;
extern const lv_image_dsc_t m3e_weather_icon_condition_rain_64;
extern const lv_image_dsc_t m3e_weather_icon_condition_heavy_rain_18;
extern const lv_image_dsc_t m3e_weather_icon_condition_heavy_rain_24;
extern const lv_image_dsc_t m3e_weather_icon_condition_heavy_rain_32;
extern const lv_image_dsc_t m3e_weather_icon_condition_heavy_rain_64;
extern const lv_image_dsc_t m3e_weather_icon_condition_thunderstorm_18;
extern const lv_image_dsc_t m3e_weather_icon_condition_thunderstorm_24;
extern const lv_image_dsc_t m3e_weather_icon_condition_thunderstorm_32;
extern const lv_image_dsc_t m3e_weather_icon_condition_thunderstorm_64;
extern const lv_image_dsc_t m3e_weather_icon_condition_snow_18;
extern const lv_image_dsc_t m3e_weather_icon_condition_snow_24;
extern const lv_image_dsc_t m3e_weather_icon_condition_snow_32;
extern const lv_image_dsc_t m3e_weather_icon_condition_snow_64;
extern const lv_image_dsc_t m3e_weather_icon_condition_sleet_18;
extern const lv_image_dsc_t m3e_weather_icon_condition_sleet_24;
extern const lv_image_dsc_t m3e_weather_icon_condition_sleet_32;
extern const lv_image_dsc_t m3e_weather_icon_condition_sleet_64;
extern const lv_image_dsc_t m3e_weather_icon_condition_wind_18;
extern const lv_image_dsc_t m3e_weather_icon_condition_wind_24;
extern const lv_image_dsc_t m3e_weather_icon_condition_wind_32;
extern const lv_image_dsc_t m3e_weather_icon_condition_wind_64;
extern const lv_image_dsc_t m3e_weather_icon_condition_hot_18;
extern const lv_image_dsc_t m3e_weather_icon_condition_hot_24;
extern const lv_image_dsc_t m3e_weather_icon_condition_hot_32;
extern const lv_image_dsc_t m3e_weather_icon_condition_hot_64;
extern const lv_image_dsc_t m3e_weather_icon_condition_unknown_18;
extern const lv_image_dsc_t m3e_weather_icon_condition_unknown_24;
extern const lv_image_dsc_t m3e_weather_icon_condition_unknown_32;
extern const lv_image_dsc_t m3e_weather_icon_condition_unknown_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_location_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_location_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_location_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_location_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_chevron_right_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_chevron_right_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_chevron_right_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_chevron_right_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_arrow_high_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_arrow_high_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_arrow_high_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_arrow_high_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_arrow_low_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_arrow_low_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_arrow_low_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_arrow_low_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_thermometer_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_thermometer_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_thermometer_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_thermometer_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_humidity_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_humidity_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_humidity_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_humidity_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_wind_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_wind_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_wind_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_wind_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_uv_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_uv_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_uv_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_uv_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_sunrise_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_sunrise_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_sunrise_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_sunrise_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_sunset_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_sunset_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_sunset_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_sunset_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_clock_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_clock_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_clock_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_clock_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_precipitation_bars_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_precipitation_bars_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_precipitation_bars_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_precipitation_bars_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_details_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_details_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_details_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_details_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_warning_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_warning_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_warning_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_warning_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_offline_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_offline_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_offline_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_offline_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_refresh_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_refresh_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_refresh_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_refresh_64;
extern const lv_image_dsc_t m3e_weather_icon_utility_retry_18;
extern const lv_image_dsc_t m3e_weather_icon_utility_retry_24;
extern const lv_image_dsc_t m3e_weather_icon_utility_retry_32;
extern const lv_image_dsc_t m3e_weather_icon_utility_retry_64;
}

namespace m3e {

const lv_image_dsc_t* weather_icon_asset(
    generated::WeatherIcon icon,
    std::int32_t size) {
    static constexpr std::array<std::array<const lv_image_dsc_t*, 4>,
        static_cast<std::size_t>(generated::WeatherIcon::count)> kAssets{{
    {{&m3e_weather_icon_condition_clear_day_18, &m3e_weather_icon_condition_clear_day_24, &m3e_weather_icon_condition_clear_day_32, &m3e_weather_icon_condition_clear_day_64}},
    {{&m3e_weather_icon_condition_clear_night_18, &m3e_weather_icon_condition_clear_night_24, &m3e_weather_icon_condition_clear_night_32, &m3e_weather_icon_condition_clear_night_64}},
    {{&m3e_weather_icon_condition_partly_cloudy_day_18, &m3e_weather_icon_condition_partly_cloudy_day_24, &m3e_weather_icon_condition_partly_cloudy_day_32, &m3e_weather_icon_condition_partly_cloudy_day_64}},
    {{&m3e_weather_icon_condition_partly_cloudy_night_18, &m3e_weather_icon_condition_partly_cloudy_night_24, &m3e_weather_icon_condition_partly_cloudy_night_32, &m3e_weather_icon_condition_partly_cloudy_night_64}},
    {{&m3e_weather_icon_condition_cloudy_18, &m3e_weather_icon_condition_cloudy_24, &m3e_weather_icon_condition_cloudy_32, &m3e_weather_icon_condition_cloudy_64}},
    {{&m3e_weather_icon_condition_overcast_18, &m3e_weather_icon_condition_overcast_24, &m3e_weather_icon_condition_overcast_32, &m3e_weather_icon_condition_overcast_64}},
    {{&m3e_weather_icon_condition_fog_18, &m3e_weather_icon_condition_fog_24, &m3e_weather_icon_condition_fog_32, &m3e_weather_icon_condition_fog_64}},
    {{&m3e_weather_icon_condition_drizzle_18, &m3e_weather_icon_condition_drizzle_24, &m3e_weather_icon_condition_drizzle_32, &m3e_weather_icon_condition_drizzle_64}},
    {{&m3e_weather_icon_condition_rain_18, &m3e_weather_icon_condition_rain_24, &m3e_weather_icon_condition_rain_32, &m3e_weather_icon_condition_rain_64}},
    {{&m3e_weather_icon_condition_heavy_rain_18, &m3e_weather_icon_condition_heavy_rain_24, &m3e_weather_icon_condition_heavy_rain_32, &m3e_weather_icon_condition_heavy_rain_64}},
    {{&m3e_weather_icon_condition_thunderstorm_18, &m3e_weather_icon_condition_thunderstorm_24, &m3e_weather_icon_condition_thunderstorm_32, &m3e_weather_icon_condition_thunderstorm_64}},
    {{&m3e_weather_icon_condition_snow_18, &m3e_weather_icon_condition_snow_24, &m3e_weather_icon_condition_snow_32, &m3e_weather_icon_condition_snow_64}},
    {{&m3e_weather_icon_condition_sleet_18, &m3e_weather_icon_condition_sleet_24, &m3e_weather_icon_condition_sleet_32, &m3e_weather_icon_condition_sleet_64}},
    {{&m3e_weather_icon_condition_wind_18, &m3e_weather_icon_condition_wind_24, &m3e_weather_icon_condition_wind_32, &m3e_weather_icon_condition_wind_64}},
    {{&m3e_weather_icon_condition_hot_18, &m3e_weather_icon_condition_hot_24, &m3e_weather_icon_condition_hot_32, &m3e_weather_icon_condition_hot_64}},
    {{&m3e_weather_icon_condition_unknown_18, &m3e_weather_icon_condition_unknown_24, &m3e_weather_icon_condition_unknown_32, &m3e_weather_icon_condition_unknown_64}},
    {{&m3e_weather_icon_utility_location_18, &m3e_weather_icon_utility_location_24, &m3e_weather_icon_utility_location_32, &m3e_weather_icon_utility_location_64}},
    {{&m3e_weather_icon_utility_chevron_right_18, &m3e_weather_icon_utility_chevron_right_24, &m3e_weather_icon_utility_chevron_right_32, &m3e_weather_icon_utility_chevron_right_64}},
    {{&m3e_weather_icon_utility_arrow_high_18, &m3e_weather_icon_utility_arrow_high_24, &m3e_weather_icon_utility_arrow_high_32, &m3e_weather_icon_utility_arrow_high_64}},
    {{&m3e_weather_icon_utility_arrow_low_18, &m3e_weather_icon_utility_arrow_low_24, &m3e_weather_icon_utility_arrow_low_32, &m3e_weather_icon_utility_arrow_low_64}},
    {{&m3e_weather_icon_utility_thermometer_18, &m3e_weather_icon_utility_thermometer_24, &m3e_weather_icon_utility_thermometer_32, &m3e_weather_icon_utility_thermometer_64}},
    {{&m3e_weather_icon_utility_humidity_18, &m3e_weather_icon_utility_humidity_24, &m3e_weather_icon_utility_humidity_32, &m3e_weather_icon_utility_humidity_64}},
    {{&m3e_weather_icon_utility_wind_18, &m3e_weather_icon_utility_wind_24, &m3e_weather_icon_utility_wind_32, &m3e_weather_icon_utility_wind_64}},
    {{&m3e_weather_icon_utility_uv_18, &m3e_weather_icon_utility_uv_24, &m3e_weather_icon_utility_uv_32, &m3e_weather_icon_utility_uv_64}},
    {{&m3e_weather_icon_utility_sunrise_18, &m3e_weather_icon_utility_sunrise_24, &m3e_weather_icon_utility_sunrise_32, &m3e_weather_icon_utility_sunrise_64}},
    {{&m3e_weather_icon_utility_sunset_18, &m3e_weather_icon_utility_sunset_24, &m3e_weather_icon_utility_sunset_32, &m3e_weather_icon_utility_sunset_64}},
    {{&m3e_weather_icon_utility_clock_18, &m3e_weather_icon_utility_clock_24, &m3e_weather_icon_utility_clock_32, &m3e_weather_icon_utility_clock_64}},
    {{&m3e_weather_icon_utility_precipitation_bars_18, &m3e_weather_icon_utility_precipitation_bars_24, &m3e_weather_icon_utility_precipitation_bars_32, &m3e_weather_icon_utility_precipitation_bars_64}},
    {{&m3e_weather_icon_utility_details_18, &m3e_weather_icon_utility_details_24, &m3e_weather_icon_utility_details_32, &m3e_weather_icon_utility_details_64}},
    {{&m3e_weather_icon_utility_warning_18, &m3e_weather_icon_utility_warning_24, &m3e_weather_icon_utility_warning_32, &m3e_weather_icon_utility_warning_64}},
    {{&m3e_weather_icon_utility_offline_18, &m3e_weather_icon_utility_offline_24, &m3e_weather_icon_utility_offline_32, &m3e_weather_icon_utility_offline_64}},
    {{&m3e_weather_icon_utility_refresh_18, &m3e_weather_icon_utility_refresh_24, &m3e_weather_icon_utility_refresh_32, &m3e_weather_icon_utility_refresh_64}},
    {{&m3e_weather_icon_utility_retry_18, &m3e_weather_icon_utility_retry_24, &m3e_weather_icon_utility_retry_32, &m3e_weather_icon_utility_retry_64}},
    }};
    const auto index = static_cast<std::size_t>(icon);
    if (index >= kAssets.size()) return nullptr;
    const auto size_index = size <= 18 ? 0U : size <= 24 ? 1U : size <= 32 ? 2U : 3U;
    return kAssets[index][size_index];
}

}  // namespace m3e
