#!/usr/bin/env python3
"""Generate and verify the deterministic Wallet boarding-code asset."""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
import sys
from pathlib import Path

from doodad_cli.parallax_image import write_png_rgb888


ROOT = Path(__file__).resolve().parents[1]
ASSET_DIRECTORY = ROOT / "apps" / "wallet" / "assets"
PREVIEW = ASSET_DIRECTORY / "boarding-pass-qr.png"
MANIFEST = ASSET_DIRECTORY / "wallet-assets.json"
EMBEDDED_C = (
    ROOT
    / "components"
    / "m3e_lvgl"
    / "src"
    / "assets"
    / "wallet_qr_asset.c"
)
MODULE_PIXELS = 3
MATRIX = (
    ".............................................",
    ".............................................",
    ".............................................",
    ".............................................",
    "....#######.###.##.#.###.#..###...#######....",
    "....#.....#..#.###....#.#..#.####.#.....#....",
    "....#.###.#..#........#..#.###.#..#.###.#....",
    "....#.###.#.#..#.#.#.#..#.#.####..#.###.#....",
    "....#.###.#.##..##..#..##.#.##....#.###.#....",
    "....#.....#.#.#.#.#.#...#.#..#.##.#.....#....",
    "....#######.#.#.#.#.#.#.#.#.#.#.#.#######....",
    "............#..#..#.#...#..#####.............",
    "....#...#.###..####.#...#.##.#.#######..#....",
    ".....#.###.#####.##..##..#.###...#...#..#....",
    ".....##.#.##.#.#...#.#.#.#..#.#..#...####....",
    "....##.##..##..#.#.##.#...##.#.#..##...#.....",
    "....####.###..####..#####..##..##.#.#........",
    "....#.#.#....###..#.....###..#.###..#.#.#....",
    "....##.#.####.#.####.#..#####...#....#..#....",
    ".......#.#.#####.#.#.#.....###......#.##.....",
    ".....###..#.###..##...#.#...#..#..#.###.#....",
    "......###..####.###.#.##.##.#...#.##..###....",
    ".....####.####....#.##.#.##.#.#..#.#.###.....",
    "......####............#.#..#.####....#.##....",
    "....#.##..#.#..###.#####..##.###...###.##....",
    ".....#.#.#.....###.######.##.#.#...#...##....",
    ".....#....#.#..#.#..#.#.###...#.###.#...#....",
    "....#...##.#.####..##......###.#.#..#..#.....",
    ".....###.##.####..#.#....#...#..##..###.#....",
    "....#.#.#....#..#.#...#.....#.#...#...#......",
    "........#######...##.###.##.....##.#..##.....",
    ".......#......##.#.##.#.#..#######.#.#..#....",
    "....#######.#..#.#..#.#.##...#.#######.......",
    "............#..##.#.#...#.#######...#####....",
    "....#######.#..#..#..#..##..#.#.#.#.#..#.....",
    "....#.....#..###...####.#..###.##...###......",
    "....#.###.#.##.#.##...##.#.##..########.#....",
    "....#.###.#.....###.##.####.#.###...###.#....",
    "....#.###.#..#.#.##.######.##....##.#.##.....",
    "....#.....#..#..#.#...#...##.####..###.##....",
    "....#######.#.##...#.##..##...###.#.....#....",
    ".............................................",
    ".............................................",
    ".............................................",
    ".............................................",
)
WIDTH = len(MATRIX[0]) * MODULE_PIXELS
HEIGHT = len(MATRIX) * MODULE_PIXELS
HEADER = struct.Struct("<4sHHBBH")
MAGIC = b"DIMG"
FORMAT_RGB565LE = 1


def qr_rgb888() -> bytes:
    """Return a fixed, valid QR for a non-production demo boarding pass."""

    if len(MATRIX) != 45 or any(len(row) != 45 for row in MATRIX):
        raise RuntimeError("Wallet QR matrix must be exactly 45 by 45 modules")
    pixels = bytearray()
    for row in MATRIX:
        expanded = bytearray()
        for module in row:
            color = (0, 0, 0) if module == "#" else (255, 255, 255)
            expanded.extend(color * MODULE_PIXELS)
        for _ in range(MODULE_PIXELS):
            pixels.extend(expanded)
    return bytes(pixels)


def rgb888_to_rgb565le(pixels: bytes) -> bytes:
    output = bytearray()
    for index in range(0, len(pixels), 3):
        red, green, blue = pixels[index : index + 3]
        packed = ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)
        output.extend(struct.pack("<H", packed))
    return bytes(output)


def dimg_payload(pixels: bytes) -> bytes:
    return HEADER.pack(
        MAGIC,
        WIDTH,
        HEIGHT,
        FORMAT_RGB565LE,
        0,
        0,
    ) + rgb888_to_rgb565le(pixels)


def c_source(payload: bytes, sha256: str) -> str:
    rows = []
    for start in range(0, len(payload), 12):
        chunk = payload[start : start + 12]
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return (
        "/* Generated by tools/generate_wallet_asset.py. */\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n\n"
        f'const char doodad_wallet_qr_sha256[] = "{sha256}";\n'
        "const uint8_t doodad_wallet_qr_dimg[] = {\n"
        + "\n".join(rows)
        + "\n};\n"
        "const size_t doodad_wallet_qr_dimg_size = "
        "sizeof(doodad_wallet_qr_dimg);\n"
    )


def generated_outputs() -> tuple[str, dict[Path, bytes]]:
    pixels = qr_rgb888()
    payload = dimg_payload(pixels)
    sha256 = hashlib.sha256(payload).hexdigest()
    descriptor = {
        "schema_version": 1,
        "assets": [
            {
                "sha256": sha256,
                "path": f"assets/{sha256}.dimg",
                "media_type": "image/vnd.doodad.rgb565le",
                "width": WIDTH,
                "height": HEIGHT,
                "encoded_bytes": len(payload),
                "decoded_bytes": WIDTH * HEIGHT * 2,
            }
        ],
    }
    return (
        sha256,
        {
            ASSET_DIRECTORY / f"{sha256}.dimg": payload,
            MANIFEST: (
                json.dumps(descriptor, indent=2, sort_keys=True) + "\n"
            ).encode(),
            EMBEDDED_C: c_source(payload, sha256).encode(),
        },
    )


def generate() -> str:
    sha256, outputs = generated_outputs()
    ASSET_DIRECTORY.mkdir(parents=True, exist_ok=True)
    for stale in ASSET_DIRECTORY.glob("*.dimg"):
        if stale not in outputs:
            stale.unlink()
    pixels = qr_rgb888()
    write_png_rgb888(PREVIEW, pixels, width=WIDTH, height=HEIGHT)
    for path, payload in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)
    return sha256


def check() -> str:
    sha256, outputs = generated_outputs()
    failures = []
    for path, expected in outputs.items():
        if not path.is_file():
            failures.append(f"missing {path.relative_to(ROOT)}")
        elif path.read_bytes() != expected:
            failures.append(f"stale {path.relative_to(ROOT)}")
    dimgs = sorted(ASSET_DIRECTORY.glob("*.dimg"))
    expected_dimg = ASSET_DIRECTORY / f"{sha256}.dimg"
    if dimgs != [expected_dimg]:
        failures.append("wallet asset directory contains stale DIMG payloads")
    if not PREVIEW.is_file():
        failures.append(f"missing {PREVIEW.relative_to(ROOT)}")
    if failures:
        raise RuntimeError("\n".join(failures))
    return sha256


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    try:
        sha256 = check() if options.check else generate()
    except (OSError, RuntimeError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1
    print(f"Wallet boarding-code asset passed: {sha256}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
