#!/usr/bin/env python3
"""Generate and verify the deterministic Media oracle artwork asset."""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
import sys
from pathlib import Path

from doodad_cli.parallax_image import write_png_rgb888


ROOT = Path(__file__).resolve().parents[1]
ASSET_DIRECTORY = ROOT / "apps" / "media" / "assets"
PREVIEW = ASSET_DIRECTORY / "night-drive.png"
MANIFEST = ASSET_DIRECTORY / "manifest.json"
EMBEDDED_C = (
    ROOT
    / "components"
    / "m3e_lvgl"
    / "src"
    / "assets"
    / "media_art_asset.c"
)
WIDTH = 96
HEIGHT = 64
HEADER = struct.Struct("<4sHHBBH")
MAGIC = b"DIMG"
FORMAT_RGB565LE = 1


def _clamp(value: int) -> int:
    return max(0, min(255, value))


def artwork_rgb888() -> bytes:
    """Return an original, deterministic synthwave city bitmap."""

    pixels = bytearray()
    buildings = (
        (0, 43, 11),
        (9, 37, 12),
        (20, 46, 10),
        (29, 33, 14),
        (42, 40, 9),
        (50, 29, 13),
        (62, 42, 12),
        (73, 35, 11),
        (84, 45, 12),
    )
    for y in range(HEIGHT):
        for x in range(WIDTH):
            red = 12 + (y * 24 // HEIGHT)
            green = 12 + (y * 8 // HEIGHT)
            blue = 38 + (x * 42 // WIDTH) + (y * 24 // HEIGHT)

            sun_dx = x - 58
            sun_dy = y - 20
            if sun_dx * sun_dx + sun_dy * sun_dy <= 14 * 14:
                stripe = (y - 7) // 4
                red = 255
                green = _clamp(196 - stripe * 18)
                blue = _clamp(92 + stripe * 22)
                if y % 4 == 2:
                    red, green, blue = 128, 45, 135

            for left, top, width in buildings:
                if left <= x < left + width and y >= top:
                    red, green, blue = 15, 18, 37
                    if (
                        y < HEIGHT - 4
                        and (x - left) % 5 in (1, 2)
                        and (y - top) % 7 in (2, 3)
                    ):
                        red, green, blue = 85, 225, 238
                    break

            if y >= 50:
                distance = abs(x - 48)
                road_half_width = 4 + (y - 50) * 2
                if distance <= road_half_width:
                    red, green, blue = 24, 20, 48
                    if distance in (
                        max(1, road_half_width - 2),
                        max(1, road_half_width - 1),
                    ):
                        red, green, blue = 239, 74, 170
                if y in (52, 57, 62):
                    red, green, blue = 68, 34, 93

            pixels.extend((_clamp(red), _clamp(green), _clamp(blue)))
    return bytes(pixels)


def rgb888_to_rgb565le(pixels: bytes) -> bytes:
    output = bytearray()
    for index in range(0, len(pixels), 3):
        red, green, blue = pixels[index : index + 3]
        packed = ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)
        output.extend(struct.pack("<H", packed))
    return bytes(output)


def dimg_payload(pixels: bytes) -> bytes:
    return HEADER.pack(
        MAGIC,
        WIDTH,
        HEIGHT,
        FORMAT_RGB565LE,
        0,
        0,
    ) + rgb888_to_rgb565le(pixels)


def c_source(payload: bytes, sha256: str) -> str:
    rows = []
    for start in range(0, len(payload), 12):
        chunk = payload[start : start + 12]
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return (
        "/* Generated by tools/generate_media_asset.py. */\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n\n"
        f'const char doodad_media_art_sha256[] = "{sha256}";\n'
        "const uint8_t doodad_media_art_dimg[] = {\n"
        + "\n".join(rows)
        + "\n};\n"
        "const size_t doodad_media_art_dimg_size = "
        "sizeof(doodad_media_art_dimg);\n"
    )


def generated_outputs() -> tuple[str, dict[Path, bytes]]:
    pixels = artwork_rgb888()
    payload = dimg_payload(pixels)
    sha256 = hashlib.sha256(payload).hexdigest()
    descriptor = {
        "schema_version": 1,
        "assets": [
            {
                "sha256": sha256,
                "path": f"assets/{sha256}.dimg",
                "media_type": "image/vnd.doodad.rgb565le",
                "width": WIDTH,
                "height": HEIGHT,
                "encoded_bytes": len(payload),
                "decoded_bytes": WIDTH * HEIGHT * 2,
            }
        ],
    }
    return (
        sha256,
        {
            ASSET_DIRECTORY / f"{sha256}.dimg": payload,
            MANIFEST: (
                json.dumps(descriptor, indent=2, sort_keys=True) + "\n"
            ).encode(),
            EMBEDDED_C: c_source(payload, sha256).encode(),
        },
    )


def generate() -> str:
    sha256, outputs = generated_outputs()
    ASSET_DIRECTORY.mkdir(parents=True, exist_ok=True)
    for stale in ASSET_DIRECTORY.glob("*.dimg"):
        if stale not in outputs:
            stale.unlink()
    pixels = artwork_rgb888()
    write_png_rgb888(PREVIEW, pixels, width=WIDTH, height=HEIGHT)
    for path, payload in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)
    return sha256


def check() -> str:
    sha256, outputs = generated_outputs()
    failures = []
    for path, expected in outputs.items():
        if not path.is_file():
            failures.append(f"missing {path.relative_to(ROOT)}")
        elif path.read_bytes() != expected:
            failures.append(f"stale {path.relative_to(ROOT)}")
    dimgs = sorted(ASSET_DIRECTORY.glob("*.dimg"))
    expected_dimg = ASSET_DIRECTORY / f"{sha256}.dimg"
    if dimgs != [expected_dimg]:
        failures.append("media asset directory contains stale DIMG payloads")
    if not PREVIEW.is_file():
        failures.append(f"missing {PREVIEW.relative_to(ROOT)}")
    if failures:
        raise RuntimeError("\n".join(failures))
    return sha256


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    try:
        sha256 = check() if options.check else generate()
    except (OSError, RuntimeError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1
    print(f"Media artwork asset passed: {sha256}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
